---
title: "Putting the First Law to Work"
output: html_document
---

<font size="4">

---

# Total and Exact Differentials
- We now know that $C_V \equiv \left( \frac {\delta U}{\delta T} \right)_V$
- This suggests that $U$ is very dependent on $V$ and $T$
- This suggests that to change $U$ we can change these variables
- This gives us a total differential
$$dU = \left( \frac{\delta U}{\delta V} \right)_T dV + \left( \frac{\delta U}{\delta T} \right)_V dT$$
- This means that
$$\Delta U = \int_{V_1}^{V_2} \left( \frac{\delta U}{\delta V} \right)_T dV+ \int_{T_1}^{T_2} \left( \frac{\delta U}{\delta T} \right)_V dT$$

$\;$

<h3> Exact Differentials </h3>
<ul>
            <li>Let's say we have a differential
                \[ df(x,y) = P\,dx + Q\,dy \]
            </li>
            <li>If these variable obey the Euler Relation
                \[ \left(\frac{\partial P}{\partial y}\right)_x = \left(\frac{\partial Q}{\partial x}\right)_y \]
                then that differential will be an exact differential
            </li>
            <li>We can illustrate this with the ideal gas law
                \[ P(V,T) = \frac{RT}{V} \]
            </li>
            <li>The differentials of all the state functions will be exact.</li>
        </ul>

---

<h2> <mark> Compressivity and Expansivity </mark> </h2>
<h3>Isothermal Compressibility (\(\kappa_T\))</h3>
<ul>
            <li>It is important that we understand how compressible substances are</li>
            <li>To quantify how compressible substances are we can look at the fractional differential change in volume due to a change in pressure
                \[ \kappa_T \equiv -\frac{1}{V} \left(\frac{\partial V}{\partial P}\right)_T \]
            </li>
        </ul>
$\;$
<h3>Isobaric Thermal Expansivity (\(\alpha\))</h3>
<ul>
            <li>It is also important to understand how the volume of a substance responds to temperature</li>
            <li>To quantify this, we define the isobaric thermal expansivity (sometimes called the expansion coefficient)
                \[ \alpha \equiv \frac{1}{V} \left(\frac{\partial V}{\partial T}\right)_P \]
            </li>
        </ul>
$\;$

::: {.graybox data-latex=""}
<h3>Partial Derivatives: The Reciprocal Rule</h3>

<ul>
            <li>Consider a function \( F\) of three variables \(x\), \(y\), and \(z\) such that we can write \( F(x,y,z)=0 \)</li>
            <li>This means that we can specify the system by knowning two of the three variables, or
                \[ dz = \left(\frac{\partial z}{\partial x}\right)_y dx + \left(\frac{\partial z}{\partial y}\right)_x dy \text{ and } dy = \left(\frac{\partial y}{\partial x}\right)_z dx + \left(\frac{\partial y}{\partial z}\right)_x dz \]
            </li>
            <li>After a lot of calculus we find that
                \[ 1=\left(\frac{\partial z}{\partial y}\right)_x \left(\frac{\partial y}{\partial z}\right)_x \text{ or } \left(\frac{\partial z}{\partial y}\right)_x = \frac{1}{\left(\frac{\partial y}{\partial z}\right)_x}\]
            </li>
        </ul>
:::

$\;$

::: {.graybox data-latex=""}
<h3>Partial Derivatives: The Cyclic Permutation Rule</h3>
        
<ul>
            <li>Along similar lines to the last we, we can generate a very useful partial differential relationship</li>
        </ul>
        
\[ \left(\frac{\partial z}{\partial x}\right)_y = -\left(\frac{\partial z}{\partial y}\right)_x \left(\frac{\partial y}{\partial x}\right)_z \]
:::

$\;$

::: {.whitebox data-latex=""}
<h3>Example 4.1</h3>
        
<p>
            Derive an expression for
            \[ \frac{\alpha}{\kappa_T} \]
            in terms of derivatives of thermodynamic functions using out partial derivative relations.
        </p>
:::

---

<a href=joule-experiment.html> <h2> The Joule Experiment </h2> </a>

---

</font>